LangString addOrReinstall ${LANG_VIETNAMESE} "Cài lại hoặc cập nhật thành phần"
LangString alreadyInstalled ${LANG_VIETNAMESE} "Morrow đã được cài đặt"
LangString alreadyInstalledLong ${LANG_VIETNAMESE} "${PRODUCTNAME} ${VERSION} đã có trên máy. Chọn thao tác và nhấn Tiếp tục."
LangString appRunning ${LANG_VIETNAMESE} "${PRODUCTNAME} đang chạy. Vui lòng đóng ứng dụng rồi thử lại."
LangString appRunningOkKill ${LANG_VIETNAMESE} "${PRODUCTNAME} đang chạy!$\nNhấn OK để đóng ứng dụng."
LangString chooseMaintenanceOption ${LANG_VIETNAMESE} "Chọn thao tác bạn muốn thực hiện."
LangString choowHowToInstall ${LANG_VIETNAMESE} "Chọn cách cài ${PRODUCTNAME}."
LangString createDesktop ${LANG_VIETNAMESE} "Tạo lối tắt trên màn hình Desktop"
LangString dontUninstall ${LANG_VIETNAMESE} "Giữ bản hiện tại và cài đè"
LangString dontUninstallDowngrade ${LANG_VIETNAMESE} "Không gỡ bản hiện tại (bộ cài không cho phép hạ phiên bản theo cách này)"
LangString failedToKillApp ${LANG_VIETNAMESE} "Không thể đóng ${PRODUCTNAME}. Vui lòng tự đóng ứng dụng rồi thử lại."
LangString installingWebview2 ${LANG_VIETNAMESE} "Đang cài WebView2..."
LangString newerVersionInstalled ${LANG_VIETNAMESE} "Máy đã có phiên bản ${PRODUCTNAME} mới hơn. Chọn thao tác và nhấn Tiếp tục."
LangString older ${LANG_VIETNAMESE} "cũ hơn"
LangString olderOrUnknownVersionInstalled ${LANG_VIETNAMESE} "Máy đã có phiên bản ${PRODUCTNAME} $R4. Chọn thao tác và nhấn Tiếp tục."
LangString silentDowngrades ${LANG_VIETNAMESE} "Không thể hạ phiên bản ở chế độ im lặng. Vui lòng mở bộ cài.$\n"
LangString unableToUninstall ${LANG_VIETNAMESE} "Không thể gỡ cài đặt!"
LangString uninstallApp ${LANG_VIETNAMESE} "Gỡ cài đặt ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_VIETNAMESE} "Gỡ bản hiện tại trước khi cài"
LangString unknown ${LANG_VIETNAMESE} "không xác định"
LangString webview2AbortError ${LANG_VIETNAMESE} "Không thể cài WebView2. Morrow cần thành phần này để chạy. Vui lòng thử lại."
LangString webview2DownloadError ${LANG_VIETNAMESE} "Không thể tải WebView2: $0"
LangString webview2DownloadSuccess ${LANG_VIETNAMESE} "Đã tải trình cài WebView2"
LangString webview2Downloading ${LANG_VIETNAMESE} "Đang tải trình cài WebView2..."
LangString webview2InstallError ${LANG_VIETNAMESE} "Không thể cài WebView2. Mã lỗi: $1"
LangString webview2InstallSuccess ${LANG_VIETNAMESE} "Đã cài WebView2 thành công"
LangString deleteAppData ${LANG_VIETNAMESE} "Xóa dữ liệu ứng dụng"

